# Generated by Django 2.1.7 on 2019-04-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='addedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='myapp.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='favorites',
            field=models.ManyToManyField(related_name='songFavorites', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='addedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='favorites',
            field=models.ManyToManyField(related_name='artistFavorites', to='myapp.User'),
        ),
    ]
